apiVersion: v1  # API group/v1 para recursos core do Kubernetes
kind: Secret  # Recurso Secret para armazenar dados sensíveis
metadata: 
  name: service-account-secret   # Nome do Secret
  annotations:
    kubernetes.io/service-account.name: pod-leitor  # Anotação para associar o Secret à conta de serviço "pod-leitor"
type: kubernetes.io/service-account-token  # Tipo do Secret para token de conta de serviço
