apiVersion: v1  # API group/v1 para recursos core do Kubernetes
kind: ServiceAccount  # Recurso ServiceAccount para criar uma conta de serviço
metadata:
  name: pod-leitor  # Nome da conta de serviço
  namespace: default  # Namespace onde a conta de serviço será criada