apiVersion: v1
kind: Pod
metadata:
  labels:
    run: girus
    day: "2"
    service: limits
    service: requests-limits
  name: girus
spec:
  containers:
  - image: ubuntu
    name: ubuntu
    args:
    - sleep 
    - "1200"
    resources:
      limits:
        cpu: "1.5"
        memory: "128Mi"
      requests:
        cpu: "0.3"
        memory: "64Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
